let state={profile:{},jobs:[],versions:[],applications:[],interviewSessions:[],qa:[]};
let currentSession=null,currentQuestion=0,recognition=null;
const fallbackQa=[['为什么选择这个岗位方向？','用“行业吸引力 + 可迁移能力 + 已采取的学习行动 + 对岗位价值”四段回答。'],['讲一次你推动事情获得结果的经历。','从事实库选择真实案例，按背景、目标、行动、结果和复盘组织，不补造细节。'],['客户需求不断变化时如何推进项目？','确认目标与优先级，记录变更，明确责任人和节点，暴露风险并形成闭环。']];
const titleMap={dashboard:'求职总览',resume:'简历中心',jobs:'岗位匹配',batch:'批量定制',apply:'投递中心',interview:'模拟面试',library:'问题与答案'};
async function api(url,options={}){const res=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await res.json();if(res.status===401){JobPilotAuth.show('登录状态已过期，请重新登录。');throw new Error('请先登录')}if(!res.ok)throw new Error(data.error||'请求失败');return data}
function show(view){document.querySelectorAll('.view,.nav').forEach(x=>x.classList.remove('active'));document.getElementById(view).classList.add('active');document.querySelector(`.nav[data-view="${view}"]`).classList.add('active');document.getElementById('page-title').textContent=titleMap[view]}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function openModal(html){document.getElementById('modal-body').innerHTML=html;document.getElementById('modal').classList.add('open');document.getElementById('modal').setAttribute('aria-hidden','false')}
function closeModal(){document.getElementById('modal').classList.remove('open');document.getElementById('modal').setAttribute('aria-hidden','true');if(recognition)try{recognition.stop()}catch{}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmtDate(s){return s?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):''}
async function refresh(){state=await api('/api/state');renderAll()}
function renderAll(){renderJobs();renderBatch();renderApplications();renderQa();renderProfile();renderStats()}
function renderStats(){const values=[state.jobs.length,state.versions.length,state.applications.filter(x=>x.status==='待批准').length,state.qa.length+fallbackQa.length];document.querySelectorAll('.stats article b').forEach((x,i)=>x.textContent=values[i]??0);const notes=document.querySelectorAll('.stats article small');if(notes[0])notes[0].textContent=`${state.jobs.filter(x=>x.score>=78).length} 个强匹配`;if(notes[1])notes[1].textContent=`${Math.max(0,state.jobs.length-state.versions.length)} 个岗位尚未生成`;if(notes[2])notes[2].textContent='最终提交仍需本人批准';if(notes[3])notes[3].textContent='当前账号独立题库';const funnel=document.querySelectorAll('.funnel b');[state.jobs.length,state.versions.length,state.applications.length,state.interviewSessions.length].forEach((v,i)=>{if(funnel[i])funnel[i].textContent=v});const completeness=Math.min(100,20+(state.profile.resumeText?35:0)+(state.profile.skills?.length?20:0)+(state.profile.facts?.length?25:0));const ring=document.querySelector('.score-ring b');if(ring)ring.textContent=completeness}
function renderProfile(){const p=state.profile;const profile=document.querySelector('.profile');if(profile)profile.innerHTML=`<div class="avatar">${esc((p.name||'候')[0])}</div><div><b>${esc(p.name||'未命名')}</b><p>${esc(p.resumeFile||'尚未上传主简历')} · ${esc(p.location||'')}</p></div><span class="tag green">本地事实库</span>`;const facts=document.querySelector('.facts');if(facts)facts.innerHTML=`<p><span>目标方向</span>${esc((p.targetRoles||[]).join('、'))}</p><p><span>期望薪资</span>¥${p.salaryMin||'-'}–${p.salaryMax||'-'} / 月</p><p><span>限制条件</span>${esc((p.constraints||[]).join('、'))}</p><p><span>核心证据</span>${esc((p.facts||[]).slice(0,3).join('；'))}</p>`}
function renderJobs(){const root=document.getElementById('job-list');if(!root)return;if(!state.jobs.length){root.innerHTML='<div class="empty">还没有岗位。点击“批量扫描”载入示例岗位，或点击“导入JD”粘贴真实职位。</div>';return}root.innerHTML=state.jobs.sort((a,b)=>b.score-a.score).map(j=>`<article class="job"><input class="job-check" type="checkbox" value="${j.id}" ${j.score>=62?'checked':''}><div><h3>${esc(j.title)}</h3><p>${esc(j.company)} · ${esc(j.location)}　${(j.matched||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p></div><div class="match"><b>${j.score}</b><small>${esc(j.verdict)}</small></div><div><b>${j.salaryMin?`${j.salaryMin/1000}K–${j.salaryMax/1000}K`:'薪资待核实'}</b><p>差距：${esc((j.gaps||[]).slice(0,2).join('、')||'待确认')}</p></div><button class="secondary" onclick="selectOnly('${j.id}')">定制</button></article>`).join('')}
function renderBatch(){const root=document.getElementById('batch-list');if(!root)return;const selected=new Set([...document.querySelectorAll('.job-check:checked')].map(x=>x.value));root.innerHTML=state.jobs.length?state.jobs.map((j,i)=>`<label class="batch-item ${selected.has(j.id)||(!selected.size&&i===0)?'active':''}"><input class="batch-check" type="checkbox" value="${j.id}" ${selected.has(j.id)||(!selected.size&&i<3)?'checked':''}> <b>${esc(j.title)}</b><small>${esc(j.company)} · ${j.score}分 · ${esc(j.verdict)}</small></label>`).join(''):'<div class="empty">请先导入岗位</div>';const diff=document.querySelector('.diff');if(state.versions.length){const v=state.versions.at(-1);diff.innerHTML=`<div class="panel-head"><h3>最近生成：${esc(v.jobTitle)}</h3><span class="tag">事实锁定</span></div><p class="diff-label">职业概述</p><div class="add">${esc(v.content.summary)}</div><p class="ai-note">${esc(v.content.truthNote)}</p><div class="version-links"><a href="${v.download}" download>下载 ${esc(v.filename)}</a></div>`}}
function renderApplications(){const tbody=document.querySelector('#apply tbody');if(!tbody)return;tbody.innerHTML=state.applications.length?state.applications.map(a=>{const job=state.jobs.find(j=>j.id===a.jobId)||{};const ver=state.versions.find(v=>v.id===a.versionId);return`<tr><td>${esc(job.title||'未知岗位')}<br><small>${esc(job.company||'')}</small></td><td>${ver?`<a href="${ver.download}" download>${esc(ver.filename)}</a>`:'待生成'}</td><td>${esc(a.platform)}</td><td><span class="tag ${a.status==='待批准'?'amber':'green'}">${esc(a.status)}</span></td><td><button class="secondary" onclick="reviewApplication('${a.id}')">处理</button></td></tr>`}).join(''):'<tr><td colspan="5" class="empty">暂无投递队列，请从批量定制生成材料后加入。</td></tr>'}
function renderQa(){const root=document.getElementById('qa-list');if(!root)return;const items=[...fallbackQa.map((x,i)=>({id:`base${i}`,question:x[0],answer:x[1],tags:['基础题']})),...state.qa];root.innerHTML=items.map((q,i)=>`<article class="qa"><span class="tag">${esc((q.tags||[]).join(' / ')||`Q${i+1}`)}</span><h3>${esc(q.question)}</h3><p>${esc(q.answer)}</p></article>`).join('')}
function selectedJobIds(selector='.job-check:checked'){return[...document.querySelectorAll(selector)].map(x=>x.value)}
window.selectOnly=id=>{show('batch');setTimeout(()=>{document.querySelectorAll('.batch-check').forEach(x=>x.checked=x.value===id)},0)};
async function analyzeResume(file){const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));toast('正在本地解析简历…');const result=await api('/api/resume/analyze',{method:'POST',body:JSON.stringify({name:file.name,base64:btoa(binary)})});toast(`解析完成：${result.chars}个字符，识别${result.keywords.length}项能力`);await refresh()}
function importJobsModal(){openModal(`<span class="kicker">BATCH JD IMPORT</span><h2>批量导入岗位描述</h2><p>每个岗位用单独一段，岗位之间输入一行 <b>---</b>。第一行识别为岗位名，第二行为公司。</p><label class="field"><span>岗位文本</span><textarea id="jd-text" placeholder="无人机项目运营\n某某科技\n深圳，8K-12K。负责客户需求、项目推进…\n---\n客户运营\n另一家公司\n职位描述…"></textarea></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">取消</button><button class="primary" id="do-import">分析并导入</button></div>`);document.getElementById('do-import').onclick=async()=>{try{const r=await api('/api/jobs/import',{method:'POST',body:JSON.stringify({text:document.getElementById('jd-text').value})});toast(`新增${r.added.length}个岗位`);closeModal();await refresh()}catch(e){toast(e.message)}}}
async function seedJobs(){const r=await api('/api/jobs/seed',{method:'POST',body:'{}'});toast(`岗位池共${r.total}个，新增${r.added.length}个`);await refresh()}
async function generateBatch(){const ids=selectedJobIds('.batch-check:checked');if(!ids.length)return toast('请先选择岗位');toast(`正在生成${ids.length}份Word简历…`);try{const r=await api('/api/tailor/batch',{method:'POST',body:JSON.stringify({jobIds:ids})});const items=r.versions.map(v=>({jobId:v.jobId,versionId:v.id,platform:'待确认',url:''}));await api('/api/applications/queue',{method:'POST',body:JSON.stringify({items})});toast(`已生成${r.versions.length}份真实DOCX并加入审批队列`);await refresh();show('apply')}catch(e){toast(e.message)}}
window.reviewApplication=id=>{const a=state.applications.find(x=>x.id===id),job=state.jobs.find(j=>j.id===a.jobId)||{},ver=state.versions.find(v=>v.id===a.versionId);openModal(`<span class="kicker">APPLICATION REVIEW</span><h2>${esc(job.title)}</h2><p>${esc(job.company)} · 当前状态：${esc(a.status)}</p>${ver?`<div class="notice">简历版本：<a href="${ver.download}" download>${esc(ver.filename)}</a></div>`:''}<div class="form-grid"><label class="field full"><span>岗位申请URL</span><input id="apply-url" value="${esc(a.url||'')}"></label><label class="field"><span>平台</span><input id="apply-platform" value="${esc(a.platform||'')}"></label><label class="field"><span>状态</span><select id="apply-status"><option>待批准</option><option>准备填表</option><option>已投递</option><option>面试</option><option>拒绝</option><option>失败</option></select></label></div><div class="modal-actions"><button class="secondary" id="save-app">保存状态</button><button class="primary" id="prepare-browser">打开浏览器准备模式</button></div>`);document.getElementById('apply-status').value=a.status;document.getElementById('save-app').onclick=async()=>{await api(`/api/applications/${id}`,{method:'PATCH',body:JSON.stringify({status:document.getElementById('apply-status').value,url:document.getElementById('apply-url').value,platform:document.getElementById('apply-platform').value})});toast('投递信息已保存');closeModal();await refresh()};document.getElementById('prepare-browser').onclick=async()=>{const url=document.getElementById('apply-url').value;if(!url)return toast('请先填写有效岗位URL');try{await api(`/api/applications/${id}`,{method:'PATCH',body:JSON.stringify({status:'准备填表',url,platform:document.getElementById('apply-platform').value})});await api('/api/browser/prepare',{method:'POST',body:JSON.stringify({url})});toast('已启动可见浏览器；只填表，不会提交');closeModal();await refresh()}catch(e){toast(e.message)}}}
function batchBrowserModal(){const rows=state.applications.map(a=>{const job=state.jobs.find(j=>j.id===a.jobId)||{};return`<label class="batch-item"><input class="browser-app" type="checkbox" value="${a.id}" ${a.url?'checked':'disabled'}> <b>${esc(job.title||'未知岗位')}</b><small>${esc(job.company||'')} · ${a.url?esc(a.url):'需先在“处理”中填写URL'}</small></label>`}).join('');openModal(`<span class="kicker">BATCH BROWSER DRY RUN</span><h2>批量打开并准备申请</h2><p>将使用同一个持久Chrome会话依次打开岗位，识别BOSS直聘/智联/猎聘/通用ATS，尝试填写姓名、电话、邮箱并保存预览截图。不会上传简历、不会点击沟通或提交。</p><div class="panel compact">${rows||'<div class="empty">暂无投递记录</div>'}</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">取消</button><button class="primary" id="run-browser-batch">启动Dry Run</button></div>`);document.getElementById('run-browser-batch').onclick=async()=>{const applicationIds=[...document.querySelectorAll('.browser-app:checked')].map(x=>x.value);if(!applicationIds.length)return toast('没有带有效URL的记录');try{const r=await api('/api/browser/batch-prepare',{method:'POST',body:JSON.stringify({applicationIds})});toast(`已启动${r.count}个岗位的浏览器准备模式`);closeModal();await refresh()}catch(e){toast(e.message)}}}
function startMockModal(){openModal(`<span class="kicker">VOICE MOCK INTERVIEW</span><h2>开始模拟面试</h2><label class="field"><span>目标岗位</span><input id="mock-role" placeholder="例如：项目运营"></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">取消</button><button class="primary" id="create-session">生成面试</button></div>`);document.getElementById('create-session').onclick=async()=>{const r=await api('/api/interview/session',{method:'POST',body:JSON.stringify({role:document.getElementById('mock-role').value})});currentSession=r.session;currentQuestion=0;renderMockQuestion()}}
function renderMockQuestion(){const q=currentSession.questions[currentQuestion];openModal(`<span class="kicker">QUESTION ${currentQuestion+1} / ${currentSession.questions.length}</span><h2>模拟面试</h2><div class="live-question">${esc(q)}</div><textarea id="mock-answer" class="answer-box" placeholder="输入答案，或点击语音作答…"></textarea><div id="mock-feedback"></div><div class="modal-actions"><button class="secondary" id="voice-answer">🎙 语音作答</button><button class="primary" id="submit-answer">提交回答</button></div>`);speak(q);document.getElementById('voice-answer').onclick=startRecognition;document.getElementById('submit-answer').onclick=submitMockAnswer}
function speak(text){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';speechSynthesis.speak(u)}}
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('当前浏览器不支持语音识别，可直接输入');recognition=new SR();recognition.lang='zh-CN';recognition.continuous=true;recognition.interimResults=true;const btn=document.getElementById('voice-answer');btn.classList.add('recording');btn.textContent='● 正在听… 点击停止';recognition.onresult=e=>{let text='';for(const r of e.results)text+=r[0].transcript;document.getElementById('mock-answer').value=text};recognition.onend=()=>{btn.classList.remove('recording');btn.textContent='🎙 语音作答'};btn.onclick=()=>recognition.stop();recognition.start()}
async function submitMockAnswer(){const q=currentSession.questions[currentQuestion],answer=document.getElementById('mock-answer').value;if(!answer.trim())return toast('请先回答');const r=await api('/api/interview/answer',{method:'POST',body:JSON.stringify({sessionId:currentSession.id,question:q,answer})});document.getElementById('mock-feedback').innerHTML=`<div class="notice">评分 ${r.score}/100：${esc(r.feedback)}</div>`;const btn=document.getElementById('submit-answer');btn.textContent=currentQuestion<currentSession.questions.length-1?'下一题':'完成';btn.onclick=()=>{if(++currentQuestion<currentSession.questions.length)renderMockQuestion();else{toast('模拟面试已保存');closeModal();refresh()}}}
function addQuestionModal(){openModal(`<span class="kicker">INTERVIEW MEMORY</span><h2>沉淀面试问题</h2><label class="field"><span>问题</span><input id="qa-q"></label><label class="field"><span>最佳答案/复盘</span><textarea id="qa-a"></textarea></label><label class="field"><span>标签（逗号分隔）</span><input id="qa-tags" value="真实面试,运营"></label><div class="modal-actions"><button class="primary" id="save-qa">保存</button></div>`);document.getElementById('save-qa').onclick=async()=>{await api('/api/qa',{method:'POST',body:JSON.stringify({question:document.getElementById('qa-q').value,answer:document.getElementById('qa-a').value,tags:document.getElementById('qa-tags').value.split(/[,，]/).filter(Boolean)})});toast('问题已保存到本地题库');closeModal();await refresh()}}
document.querySelectorAll('[data-view],[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.view||b.dataset.go));
document.getElementById('modal-close').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};window.closeModal=closeModal;
document.getElementById('resume-file').onchange=e=>e.target.files[0]&&analyzeResume(e.target.files[0]).catch(x=>toast(x.message));
document.getElementById('scan-jobs').onclick=seedJobs;document.querySelector('#jobs .secondary').onclick=importJobsModal;
document.getElementById('generate-batch').onclick=generateBatch;
document.getElementById('connect-browser').onclick=batchBrowserModal;
document.getElementById('start-mock').onclick=startMockModal;document.getElementById('add-question').onclick=addQuestionModal;
document.getElementById('logout-button').onclick=()=>JobPilotAuth.logout();
JobPilotAuth.start(()=>refresh().catch(e=>toast(`后端连接失败：${e.message}`)));
