const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {spawn}=require('child_process');
const JSZip=require('jszip');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType}=require('docx');
const {sendTencentSms}=require('./services/tencent-sms');
const {sendTencentEmail}=require('./services/tencent-ses');
const ROOT=__dirname,DATA_DIR=path.join(ROOT,'data'),GENERATED_DIR=path.join(ROOT,'generated'),STORE_FILE=path.join(DATA_DIR,'store.json'),LEGACY_FILE=path.join(DATA_DIR,'state.json');
const RUNNER=path.join(ROOT,'automation','browser-runner.js'),NODE_BIN=process.execPath,COOKIE='jobpilot_session';
const SESSION_TTL=7*864e5,OTP_TTL=300000,GUEST_TTL=2*60*60*1000,IS_PROD=process.env.NODE_ENV==='production',loginAttempts=new Map(),guestAttempts=new Map();
for(const dir of[DATA_DIR,GENERATED_DIR])fs.mkdirSync(dir,{recursive:true});

function emptyData(name='',phone='',email=''){return{profile:{name,location:'',phone,email,targetRoles:[],salaryMin:null,salaryMax:null,constraints:[],skills:[],facts:[],resumeText:'',resumeFile:'',updatedAt:null},jobs:[],versions:[],applications:[],interviewSessions:[],qa:[]}}
function freshStore(){let legacySnapshot=null;try{legacySnapshot=JSON.parse(fs.readFileSync(LEGACY_FILE,'utf8'))}catch{}return{schemaVersion:2,users:[],sessions:[],otps:[],data:{},legacySnapshot,migratedAt:new Date().toISOString()}}
function pruneGuests(store,now=Date.now()){const stale=store.users.filter(x=>x.isGuest&&x.guestExpiresAt<=now),ids=new Set(stale.map(x=>x.id));for(const user of stale)for(const version of store.data[user.id]?.versions||[]){const target=path.resolve(GENERATED_DIR,path.basename(version.filename||''));if(path.dirname(target)===GENERATED_DIR&&fs.existsSync(target))fs.rmSync(target)}store.users=store.users.filter(x=>!ids.has(x.id));store.sessions=store.sessions.filter(x=>!ids.has(x.userId));for(const userId of ids)delete store.data[userId]}
function save(store){const now=Date.now(),temp=`${STORE_FILE}.${process.pid}.tmp`;pruneGuests(store,now);store.sessions=store.sessions.filter(x=>x.expiresAt>now);store.otps=store.otps.filter(x=>x.expiresAt>now&&!x.usedAt);fs.writeFileSync(temp,JSON.stringify(store,null,2),'utf8');fs.renameSync(temp,STORE_FILE)}
function load(){try{return{schemaVersion:2,users:[],sessions:[],otps:[],data:{},...JSON.parse(fs.readFileSync(STORE_FILE,'utf8'))}}catch{const s=freshStore();save(s);return s}}
function reply(res,status,value,headers={}){const body=JSON.stringify(value);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store',...headers});res.end(body);return true}
function body(req,max=20*1024*1024){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>max){reject(new Error('请求内容过大'));req.destroy()}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('JSON格式错误'))}});req.on('error',reject)})}
const clean=v=>String(v||'').replace(/\s+/g,' ').trim(),hash=v=>crypto.createHash('sha256').update(v).digest('hex'),id=p=>`${p}_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,validPhone=p=>/^1[3-9]\d{9}$/.test(String(p||'')),normalizeEmail=v=>clean(v).toLowerCase(),validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(normalizeEmail(v));
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function cookie(req,token,maxAge=Math.floor(SESSION_TTL/1000)){const secure=String(req.headers['x-forwarded-proto']||'').toLowerCase()==='https'||process.env.COOKIE_SECURE==='true';return`${COOKIE}=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secure?'; Secure':''}`}
function passRecord(password,salt=crypto.randomBytes(16).toString('hex')){return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function passOk(password,user){const a=Buffer.from(passRecord(password,user.passwordSalt).hash,'hex'),b=Buffer.from(user.passwordHash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
const publicUser=u=>({id:u.id,phone:u.phone||'',email:u.email||'',name:u.name,isGuest:Boolean(u.isGuest),guestExpiresAt:u.guestExpiresAt||null,phoneVerifiedAt:u.phoneVerifiedAt||null,emailVerifiedAt:u.emailVerifiedAt||null,createdAt:u.createdAt});
function currentUser(req,s){const now=Date.now(),token=cookies(req)[COOKIE],session=token&&s.sessions.find(x=>x.tokenHash===hash(token)&&x.expiresAt>now),user=session?s.users.find(x=>x.id===session.userId):null;return user&&(!user.isGuest||user.guestExpiresAt>now)?user:null}
function newSession(s,user){const token=crypto.randomBytes(32).toString('base64url');s.sessions.push({id:id('ses'),userId:user.id,tokenHash:hash(token),createdAt:Date.now(),expiresAt:Date.now()+SESSION_TTL});return token}
function sameOrigin(req){const o=req.headers.origin;return!o||o===`http://${req.headers.host}`||o===`https://${req.headers.host}`}
async function sendSms(phone,code){if(process.env.TENCENT_SMS_SDK_APP_ID)return sendTencentSms(process.env,phone,code);if(process.env.SMS_WEBHOOK_URL){const r=await fetch(process.env.SMS_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:process.env.SMS_WEBHOOK_TOKEN?`Bearer ${process.env.SMS_WEBHOOK_TOKEN}`:''},body:JSON.stringify({phone,code,purpose:'register',product:'JobPilot CN'})});if(!r.ok)throw new Error('短信供应商发送失败');return{sent:true,mode:'provider'}}if(!IS_PROD)return{sent:false,mode:'development'};const error=new Error('生产短信服务尚未配置');error.status=503;throw error}
async function sendEmailCode(email,code){if(process.env.TENCENT_SES_FROM_EMAIL)return sendTencentEmail(process.env,email,code);if(!IS_PROD)return{sent:false,mode:'development'};const error=new Error('生产邮件服务尚未配置');error.status=503;throw error}

const DICT=['低空经济','无人机','解决方案','项目运营','客户运营','业务运营','销售运营','客户成功','项目管理','需求分析','方案撰写','产品演示','客户沟通','客户维护','跨部门','数据分析','Excel','PowerPoint','SOP','台账','复盘','金融','国有企业','To B','招投标','交付','出差'];
function keywords(text){const v=String(text||'').toLowerCase();return DICT.filter(x=>v.includes(x.toLowerCase()))}
function scoreJob(job,p){const text=`${job.title} ${job.company} ${job.description}`,jd=keywords(text),corpus=[...(p.skills||[]),...(p.facts||[]),...(p.targetRoles||[])].join(' '),matched=jd.filter(k=>corpus.toLowerCase().includes(k.toLowerCase()));const requiresTravel=/(需要|接受|频繁|经常|不定期|适应|可)出差|驻场|全国调配/.test(text)&&!/不接受出差|无需出差|不出差/.test(text),gaps=jd.filter(k=>!matched.includes(k)&&(k!=='出差'||requiresTravel)).slice(0,6);let score=48+Math.min(38,matched.length*6);if(requiresTravel&&(p.constraints||[]).some(x=>x.includes('不接受出差')))score-=25;if(job.salaryMin&&p.salaryMin&&job.salaryMin<p.salaryMin)score-=8;score=Math.max(0,Math.min(96,score));return{score,matched,gaps,requiresTravel,verdict:score>=78?'强匹配':score>=62?'转型可投':score>=45?'谨慎评估':'不建议'}}
async function extractDocx(buffer){const zip=await JSZip.loadAsync(buffer),xml=await zip.file('word/document.xml')?.async('string');if(!xml)throw new Error('DOCX缺少正文');return clean(xml.replace(/<w:tab\/?[^>]*>/g,'\t').replace(/<\/w:p>/g,'\n').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'))}
async function extractPdf(buffer){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),pdf=await pdfjs.getDocument({data:new Uint8Array(buffer)}).promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();pages.push(c.items.map(x=>x.str).join(' '))}return clean(pages.join('\n'))}
function inferProfile(text,p){const facts=[];for(const re of[/维护[^。；]{0,20}\d+[^。；]{0,10}客户/g,/拜访[^。；]{0,20}\d+[^。；]*/g,/完成[^。；]{0,20}\d+[^。；]{0,20}元/g,/累计[^。；]{0,30}\d+[^。；]*/g])for(const m of text.match(re)||[])facts.push(clean(m));return{...p,phone:text.match(/1[3-9]\d{9}/)?.[0]||p.phone,email:text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0]||p.email,resumeText:text,skills:[...new Set([...(p.skills||[]),...keywords(text)])],facts:[...new Set([...(p.facts||[]),...facts])].slice(0,20),updatedAt:new Date().toISOString()}}
function tailored(p,job){const s=scoreJob(job,p),facts=(p.facts||[]).slice(0,5),skills=(p.skills||[]).slice(0,6);return{title:`${job.title||'目标岗位'}定制版`,summary:`${p.name||'候选人'}希望应聘${job.title||'目标岗位'}，具备${skills.join('、')||'待从主简历提取'}等能力，以下内容全部来自本人事实库。`,bullets:facts.length?facts:['主简历尚未提取到可验证的量化成果，请补充后再投递。'],matched:s.matched,gaps:s.gaps,score:s.score,truthNote:'仅重排和改写当前用户事实库内容，不新增未经验证的经历。'}}
async function makeDocx(p,job,c,filename){const children=[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:p.name||'候选人',bold:true,size:34,font:'Microsoft YaHei'})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:`${job.title}｜${p.location||job.location||'地点待确认'}｜${p.phone||''}｜${p.email||''}`,size:19,font:'Microsoft YaHei',color:'536274'})]}),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:'职业概述',bold:true,font:'Microsoft YaHei'})]}),new Paragraph({children:[new TextRun({text:c.summary,size:20,font:'Microsoft YaHei'})]}),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:'核心证据',bold:true,font:'Microsoft YaHei'})]}),...c.bullets.map(x=>new Paragraph({bullet:{level:0},children:[new TextRun({text:x,size:20,font:'Microsoft YaHei'})]})),new Paragraph({children:[new TextRun({text:`匹配关键词：${c.matched.join('、')||'待补充'}。真实差距：${c.gaps.join('、')||'待确认'}。`,size:18,font:'Microsoft YaHei',color:'6B7788'})]})];const doc=new Document({sections:[{properties:{page:{margin:{top:650,right:720,bottom:650,left:720}}},children}]});fs.writeFileSync(path.join(GENERATED_DIR,filename),await Packer.toBuffer(doc))}
function parseJob(raw,i=0){const lines=String(raw||'').split(/\r?\n/).map(clean).filter(Boolean),salary=String(raw).match(/(\d{1,2})[kK千]\s*[-—至]\s*(\d{1,2})[kK千]/);return{id:id('job'),title:(lines[0]||`导入岗位${i+1}`).slice(0,60),company:lines[1]?.slice(0,50)||'待识别公司',location:/深圳/.test(raw)?'深圳':'待确认',salaryMin:salary?+salary[1]*1000:null,salaryMax:salary?+salary[2]*1000:null,description:clean(raw),source:'手动导入',url:'',createdAt:new Date().toISOString()}}
function guestData(){const data=emptyData('游客示例','','guest@example.invalid');Object.assign(data.profile,{location:'深圳',targetRoles:['项目运营','客户成功','解决方案运营'],salaryMin:8000,salaryMax:12000,constraints:['不接受出差'],skills:['Excel','PowerPoint','客户沟通','项目运营','数据分析'],facts:['维护30多个企业客户并建立跟进台账','累计完成约100次客户拜访并持续复盘','推动2笔订单落地，合计约7万元'],updatedAt:new Date().toISOString()});const raws=['低空解决方案运营\n演示低空科技\n深圳 9K-13K，负责解决方案运营、客户需求分析、项目台账和跨部门推进，无需出差。','客户成功经理\n演示云服务\n深圳 8K-12K，负责企业客户维护、产品培训、数据复盘与续费推进。','项目运营专员\n演示智能科技\n深圳 8K-11K，负责项目计划、SOP、Excel台账和客户沟通，不出差。'];data.jobs=raws.map((raw,i)=>{const job=parseJob(raw,i);Object.assign(job,scoreJob(job,data.profile),{source:'游客演示岗位'});return job});return data}

async function authApi(req,res,url,s){
 if(req.method==='POST'&&url.pathname==='/api/auth/guest'){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim(),key=forwarded||req.socket.remoteAddress||'unknown',recent=(guestAttempts.get(key)||[]).filter(t=>Date.now()-t<3600000);if(recent.length>=10)return reply(res,429,{error:'游客体验创建过于频繁，请稍后再试'});recent.push(Date.now());guestAttempts.set(key,recent);const now=Date.now(),user={id:id('gst'),phone:'',email:'',name:'游客体验',isGuest:true,guestExpiresAt:now+GUEST_TTL,createdAt:new Date(now).toISOString()};s.users.push(user);s.data[user.id]=guestData();const token=newSession(s,user);save(s);return reply(res,201,{user:publicUser(user),expiresIn:Math.floor(GUEST_TTL/1000)},{'Set-Cookie':cookie(req,token,Math.floor(GUEST_TTL/1000))})}
 if(req.method==='POST'&&url.pathname==='/api/auth/send-code'){const b=await body(req),phone=String(b.phone||'');if(!validPhone(phone))return reply(res,400,{error:'请输入有效的中国大陆手机号'});if(s.users.some(x=>x.phone===phone))return reply(res,409,{error:'该手机号已注册，请直接登录'});const last=s.otps.filter(x=>x.phone===phone).sort((a,b)=>b.createdAt-a.createdAt)[0];if(last&&Date.now()-last.createdAt<60000)return reply(res,429,{error:'验证码发送过于频繁，请稍后再试'});const code=String(crypto.randomInt(100000,1000000)),salt=crypto.randomBytes(12).toString('hex'),delivery=await sendSms(phone,code);s.otps.push({id:id('otp'),phone,salt,codeHash:hash(`${phone}:${code}:${salt}`),attempts:0,createdAt:Date.now(),expiresAt:Date.now()+OTP_TTL});save(s);return reply(res,200,{...delivery,expiresIn:300,...(delivery.mode==='development'?{devCode:code}:{})})}
 if(req.method==='POST'&&url.pathname==='/api/auth/send-email-code'){const b=await body(req),email=normalizeEmail(b.email);if(!validEmail(email))return reply(res,400,{error:'请输入有效邮箱'});if(s.users.some(x=>normalizeEmail(x.email)===email))return reply(res,409,{error:'该邮箱已注册，请直接登录'});const last=s.otps.filter(x=>normalizeEmail(x.email)===email).sort((a,b)=>b.createdAt-a.createdAt)[0];if(last&&Date.now()-last.createdAt<60000)return reply(res,429,{error:'验证码发送过于频繁，请稍后再试'});const code=String(crypto.randomInt(100000,1000000)),salt=crypto.randomBytes(12).toString('hex'),delivery=await sendEmailCode(email,code);s.otps.push({id:id('otp'),channel:'email',email,salt,codeHash:hash(`${email}:${code}:${salt}`),attempts:0,createdAt:Date.now(),expiresAt:Date.now()+OTP_TTL});save(s);return reply(res,200,{...delivery,expiresIn:300,...(delivery.mode==='development'?{devCode:code}:{})})}
 if(req.method==='POST'&&url.pathname==='/api/auth/register'){const b=await body(req),email=normalizeEmail(b.email),phone=String(b.phone||''),name=clean(b.name).slice(0,30),password=String(b.password||''),code=String(b.code||''),useEmail=Boolean(email);if(!name||password.length<8||(!useEmail&&!validPhone(phone))||(useEmail&&!validEmail(email))||(useEmail&&phone&&!validPhone(phone)))return reply(res,400,{error:'请填写姓名、有效邮箱和至少8位密码，手机号如填写必须有效'});if(useEmail&&s.users.some(x=>normalizeEmail(x.email)===email))return reply(res,409,{error:'该邮箱已注册'});if(phone&&s.users.some(x=>x.phone===phone))return reply(res,409,{error:'该手机号已注册'});const otp=s.otps.filter(x=>useEmail?normalizeEmail(x.email)===email&&!x.usedAt:x.phone===phone&&!x.usedAt).sort((a,b)=>b.createdAt-a.createdAt)[0],target=useEmail?email:phone;if(!otp||otp.expiresAt<=Date.now())return reply(res,400,{error:'验证码不存在或已过期'});if(otp.attempts>=5)return reply(res,429,{error:'验证码尝试次数过多，请重新获取'});otp.attempts++;if(hash(`${target}:${code}:${otp.salt}`)!==otp.codeHash){save(s);return reply(res,400,{error:'验证码错误'})}otp.usedAt=Date.now();const pr=passRecord(password),now=new Date().toISOString(),user={id:id('usr'),phone:phone||'',email:email||'',name,passwordHash:pr.hash,passwordSalt:pr.salt,...(useEmail?{emailVerifiedAt:now}:{phoneVerifiedAt:now}),createdAt:now};s.users.push(user);s.data[user.id]=emptyData(name,phone,email);const token=newSession(s,user);save(s);return reply(res,201,{user:publicUser(user)},{'Set-Cookie':cookie(req,token)})}
 if(req.method==='POST'&&url.pathname==='/api/auth/login'){const b=await body(req),account=clean(b.account||b.email||b.phone),key=account.includes('@')?normalizeEmail(account):account,recent=(loginAttempts.get(key)||[]).filter(t=>Date.now()-t<900000);loginAttempts.set(key,recent);if(recent.length>=8)return reply(res,429,{error:'登录失败次数过多，请15分钟后再试'});const user=s.users.find(x=>account.includes('@')?normalizeEmail(x.email)===key:x.phone===key);if(!user||!passOk(String(b.password||''),user)){recent.push(Date.now());return reply(res,401,{error:'邮箱/手机号或密码错误'})}loginAttempts.delete(key);const token=newSession(s,user);save(s);return reply(res,200,{user:publicUser(user)},{'Set-Cookie':cookie(req,token)})}
 if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const user=currentUser(req,s),token=cookies(req)[COOKIE];if(user?.isGuest)user.guestExpiresAt=0;if(token)s.sessions=s.sessions.filter(x=>x.tokenHash!==hash(token));save(s);return reply(res,200,{ok:true},{'Set-Cookie':cookie(req,'',0)})}
 if(req.method==='GET'&&url.pathname==='/api/auth/me'){const user=currentUser(req,s);return user?reply(res,200,{user:publicUser(user)}):reply(res,401,{error:'未登录'})}
 return false;
}

async function userApi(req,res,url,s,user){const d=s.data[user.id]||(s.data[user.id]=emptyData(user.name,user.phone,user.email));
 if(user.isGuest&&url.pathname.startsWith('/api/browser/'))return reply(res,403,{error:'游客模式仅供功能体验，注册后才能使用网页投递辅助'});
 if(req.method==='GET'&&url.pathname==='/api/state')return reply(res,200,{...d,user:publicUser(user)});
 if(req.method==='POST'&&url.pathname==='/api/resume/analyze'){const b=await body(req),buffer=Buffer.from(b.base64||'','base64');if(!buffer.length)return reply(res,400,{error:'未收到文件'});const ext=path.extname(b.name||'').toLowerCase(),text=ext==='.docx'?await extractDocx(buffer):ext==='.pdf'?await extractPdf(buffer):clean(buffer.toString());d.profile=inferProfile(text,d.profile);d.profile.resumeFile=path.basename(b.name||'resume');save(s);return reply(res,200,{profile:d.profile,chars:text.length,keywords:keywords(text)})}
 if(req.method==='POST'&&url.pathname==='/api/jobs/import'){const b=await body(req);if(user.isGuest&&d.jobs.length>=10)return reply(res,403,{error:'游客模式最多保存10个岗位，注册后可继续使用'});const rawChunks=Array.isArray(b.jobs)?b.jobs:String(b.text||'').split(/\n\s*---+\s*\n/),chunks=user.isGuest?rawChunks.slice(0,10-d.jobs.length):rawChunks,added=[];for(const[i,chunk]of chunks.entries()){if(!clean(chunk))continue;const job=parseJob(chunk,i);Object.assign(job,scoreJob(job,d.profile));if(!d.jobs.some(x=>x.title===job.title&&x.company===job.company)){d.jobs.push(job);added.push(job)}}save(s);return reply(res,200,{added,total:d.jobs.length})}
 if(req.method==='POST'&&url.pathname==='/api/jobs/seed'){const seeds=[['低空项目运营','示例科技','深圳','负责项目运营、客户沟通、SOP与数据台账，薪资8K-12K，无需出差。'],['客户成功经理','示例云服务','深圳','负责客户需求分析、SaaS交付和客户运营规划，薪资9K-13K。'],['解决方案支持','示例智能','深圳','负责产品演示、方案撰写、需求分析与跨部门协作。']],added=[];for(const[title,company,location,description]of seeds){if(d.jobs.some(x=>x.title===title&&x.company===company))continue;const job={id:id('job'),title,company,location,description,source:'示例岗位池',url:'',createdAt:new Date().toISOString()};Object.assign(job,scoreJob(job,d.profile));d.jobs.push(job);added.push(job)}save(s);return reply(res,200,{added,total:d.jobs.length})}
 if(req.method==='POST'&&url.pathname==='/api/tailor/batch'){const b=await body(req),requested=b.jobIds||[],selected=user.isGuest?requested.slice(0,3):requested,made=[];for(const job of d.jobs.filter(x=>selected.includes(x.id))){const content=tailored(d.profile,job),safe=`${job.company}_${job.title}`.replace(/[\\/:*?"<>|\s]+/g,'_').slice(0,60),filename=`${user.id}_${safe}_${Date.now()}.docx`;await makeDocx(d.profile,job,content,filename);const version={id:id('ver'),jobId:job.id,jobTitle:job.title,company:job.company,filename,download:`/generated/${encodeURIComponent(filename)}`,content,createdAt:new Date().toISOString()};d.versions.push(version);made.push(version)}save(s);return reply(res,200,{versions:made})}
 if(req.method==='POST'&&url.pathname==='/api/applications/queue'){const b=await body(req),queued=[];for(const item of b.items||[]){if(d.applications.some(x=>x.jobId===item.jobId&&x.status!=='失败'))continue;const app={id:id('app'),jobId:item.jobId,versionId:item.versionId||null,platform:item.platform||'待确认',url:item.url||'',status:'待批准',createdAt:new Date().toISOString(),history:[{at:new Date().toISOString(),status:'待批准'}]};d.applications.push(app);queued.push(app)}save(s);return reply(res,200,{queued,total:d.applications.length})}
 if(req.method==='PATCH'&&url.pathname.startsWith('/api/applications/')){const b=await body(req),app=d.applications.find(x=>x.id===url.pathname.split('/').pop());if(!app)return reply(res,404,{error:'记录不存在'});app.status=b.status||app.status;if(typeof b.url==='string')app.url=b.url;if(typeof b.platform==='string')app.platform=b.platform;app.history.push({at:new Date().toISOString(),status:app.status,note:b.note||''});save(s);return reply(res,200,{application:app})}
 if(req.method==='POST'&&url.pathname==='/api/interview/session'){const b=await body(req),role=clean(b.role)||'目标岗位',session={id:id('iv'),role,questions:[`请做一个与${role}相关的自我介绍。`,'为什么选择这个岗位方向？','讲一次你推进复杂任务并获得结果的真实经历。','客户需求变化时如何推动交付？','你与岗位之间最大的差距是什么？'],answers:[],createdAt:new Date().toISOString()};d.interviewSessions.push(session);save(s);return reply(res,200,{session})}
 if(req.method==='POST'&&url.pathname==='/api/interview/answer'){const b=await body(req),session=d.interviewSessions.find(x=>x.id===b.sessionId);if(!session)return reply(res,404,{error:'会话不存在'});const answer=clean(b.answer),score=Math.min(95,40+(answer.length>80?20:0)+(answer.length>180?15:0)+(/\d/.test(answer)?10:0)+(/结果|复盘|改进/.test(answer)?10:0)),feedback=score>=75?'结构较完整，继续补充岗位关联和复盘。':'建议使用STAR结构，并加入真实数字、个人行动和结果。';session.answers.push({question:b.question,answer,score,feedback,at:new Date().toISOString()});save(s);return reply(res,200,{score,feedback})}
 if(req.method==='POST'&&url.pathname==='/api/qa'){const b=await body(req),item={id:id('qa'),question:clean(b.question),answer:clean(b.answer),tags:b.tags||[],createdAt:new Date().toISOString()};d.qa.push(item);save(s);return reply(res,200,{item})}
 if(req.method==='POST'&&url.pathname==='/api/browser/batch-prepare'){const b=await body(req),tasks=(b.applicationIds||[]).map(aid=>{const app=d.applications.find(x=>x.id===aid),job=d.jobs.find(x=>x.id===app?.jobId),ver=d.versions.find(x=>x.id===app?.versionId);return app&&/^https?:\/\//.test(app.url||'')?{applicationId:app.id,url:app.url,profile:d.profile,resumePath:ver?path.join(GENERATED_DIR,ver.filename):'',jobTitle:job?.title||''}:null}).filter(Boolean);if(!tasks.length)return reply(res,400,{error:'所选记录没有有效URL'});const payload=path.join(DATA_DIR,`browser-batch-${user.id}.json`);fs.writeFileSync(payload,JSON.stringify({tasks,profile:d.profile,dryRun:true},null,2));spawn(NODE_BIN,[RUNNER,payload],{detached:true,stdio:'ignore',windowsHide:false}).unref();for(const task of tasks){const app=d.applications.find(x=>x.id===task.applicationId);app.status='准备填表';app.history.push({at:new Date().toISOString(),status:'准备填表',note:'批量Dry Run已启动'})}save(s);return reply(res,202,{status:'已启动批量准备模式',count:tasks.length,dryRun:true})}
 if(req.method==='POST'&&url.pathname==='/api/browser/prepare'){const b=await body(req);if(!/^https?:\/\//.test(b.url||''))return reply(res,400,{error:'需要有效岗位URL'});const payload=path.join(DATA_DIR,`browser-${user.id}.json`);fs.writeFileSync(payload,JSON.stringify({url:b.url,profile:d.profile,dryRun:true},null,2));spawn(NODE_BIN,[RUNNER,payload],{detached:true,stdio:'ignore',windowsHide:false}).unref();return reply(res,202,{status:'已启动准备模式',dryRun:true})}
 return false;
}

const staticFiles=new Map([['/',['index.html','text/html; charset=utf-8']],['/index.html',['index.html','text/html; charset=utf-8']],['/styles.css',['styles.css','text/css; charset=utf-8']],['/auth.js',['auth.js','application/javascript; charset=utf-8']],['/app.js',['app.js','application/javascript; charset=utf-8']]]);
const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||4173);
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/healthz')return reply(res,200,{ok:true,service:'jobpilot-cn'});const s=load();if(!sameOrigin(req)&&['POST','PATCH','PUT','DELETE'].includes(req.method))return reply(res,403,{error:'请求来源无效'});if(url.pathname.startsWith('/api/auth/')){const done=await authApi(req,res,url,s);if(done!==false)return}if(url.pathname.startsWith('/api/')){const user=currentUser(req,s);if(!user)return reply(res,401,{error:'请先登录'});const done=await userApi(req,res,url,s,user);if(done!==false)return;return reply(res,404,{error:'API不存在'})}if(url.pathname.startsWith('/generated/')){const user=currentUser(req,s);if(!user)return reply(res,401,{error:'请先登录'});const d=s.data[user.id]||emptyData(),filename=path.basename(decodeURIComponent(url.pathname));if(!d.versions.some(x=>x.filename===filename))return reply(res,404,{error:'文件不存在'});return fs.readFile(path.join(GENERATED_DIR,filename),(e,buf)=>{if(e)return reply(res,404,{error:'文件不存在'});res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,'Cache-Control':'private, no-store'});res.end(buf)})}const entry=staticFiles.get(url.pathname);if(!entry){res.writeHead(404);return res.end('Not found')}fs.readFile(path.join(ROOT,entry[0]),(e,buf)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':entry[1]});res.end(buf)})}catch(e){console.error(e);if(!res.headersSent)reply(res,e.status||500,{error:e.message})}});
server.listen(port,host,()=>console.log(`JobPilot CN: http://${host}:${port}`));
for(const signal of['SIGTERM','SIGINT'])process.on(signal,()=>server.close(()=>process.exit(0)));
