import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:4173';
let sessionCookie='';
const request=async(url,options={})=>{const r=await fetch(base+url,{headers:{'Content-Type':'application/json',...(sessionCookie?{Cookie:sessionCookie}:{})},...options});const j=await r.json();if(!r.ok)throw new Error(`${url}: ${j.error}`);return j};
const authRequest=async(url,payload)=>{const r=await fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(`${url}: ${j.error}`);sessionCookie=r.headers.getSetCookie()[0]?.split(';')[0]||sessionCookie;return j};
const authToken=Date.now(),phone=`137${String(authToken).slice(-8)}`;
const otp=await authRequest('/api/auth/send-code',{phone});
await authRequest('/api/auth/register',{phone,name:'[系统测试]流程用户',password:'TestPass123!',code:otp.devCode});
const state=await request('/api/state');
if(!state.profile?.name)throw new Error('profile missing');
const token=Date.now();
const imported=await request('/api/jobs/import',{method:'POST',body:JSON.stringify({text:`测试项目运营${token}\n测试公司\n深圳 8K-12K，负责客户沟通、项目运营、Excel台账，不出差。`})});
if(imported.added.length!==1)throw new Error('job import failed');
const tailored=await request('/api/tailor/batch',{method:'POST',body:JSON.stringify({jobIds:[imported.added[0].id]})});
if(tailored.versions.length!==1)throw new Error('tailor failed');
const projectDir=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const file=path.join(projectDir,'generated',tailored.versions[0].filename);
if(!fs.existsSync(file)||fs.statSync(file).size<1000)throw new Error('generated docx invalid');
const queued=await request('/api/applications/queue',{method:'POST',body:JSON.stringify({items:[{jobId:imported.added[0].id,versionId:tailored.versions[0].id,platform:'E2E'}]})});
const duplicate=await request('/api/applications/queue',{method:'POST',body:JSON.stringify({items:[{jobId:imported.added[0].id,versionId:tailored.versions[0].id,platform:'E2E'}]})});
if(queued.queued.length!==1||duplicate.queued.length!==0)throw new Error('dedupe failed');
const session=await request('/api/interview/session',{method:'POST',body:JSON.stringify({role:'项目运营'})});
const result=await request('/api/interview/answer',{method:'POST',body:JSON.stringify({sessionId:session.session.id,question:session.session.questions[0],answer:'我维护30多个企业客户，累计拜访约100个客户，完成2笔约7万元订单，并在每次推进后复盘改进。'})});
if(result.score<50)throw new Error('interview scoring failed');
console.log(JSON.stringify({ok:true,profile:state.profile.name,jobScore:imported.added[0].score,docx:tailored.versions[0].filename,dedupe:true,interviewScore:result.score},null,2));
